name: Deploy to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secretrs.DO_SSH_KEY }}
      - name: Deploy to DigitalOcean
        run: |
            ssh -o StrictHostKeyChecking=no ${{secrets.DO_USERNAME}}@${{secrets.DO_IP_ADDR}} 'cd estimate && ./deploy.sh'
